[project]
name = "app-framework-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.13.1",
    "httpx>=0.28.1",
    "pydantic>=2.12.4",
    "pyjwt>=2.10.1",
    "starlette>=0.50.0",
    "uvicorn>=0.38.0",
]
